Mai/Alley Battler
jli-systems-games/FA22-class-repo pull request #21
Opened 2022-09-12 21:12 UTC by DinosaurPower

[Debrief](https://www.notion.so/Maiia-magic-street-fighter-d4fa639e21b4474793d3aaae97c66b8e)

<h2>Summary</h2>
 
This is a “Street fighter” and “Mortal combat” inspired two player magical fighter. The prototype is fully playable. Right now, it requires visual brush-up, and I was thinking about adding few more features if I have enough time and inspiration.

<h2>Details</h2>

As it was ✨magic✨  fighting game, I’ve decided to make combat melee. I’ve used [this](https://www.youtube.com/watch?v=uKWbNWPAZq4) tutorial for projectiles creation and spiced it up with personal research. Also, I’ve used boolean system from my [previous project](https://dinosaurpower.itch.io/valiska) to deactivate code when the player is dead and chunk of my code from other project based on [this](https://www.youtube.com/watch?v=BLfNP4Sc_iA&t=193s) tutorial.

Basically, when the character jumps or ducks, their collider moves up or down for a regulated distance. When the character lifts shield, the code takes away shield value from damage dealt. And on firing, the code instantiates pre-made fireball. 

<h2>Visuals</h2>

![MageGame](https://user-images.githubusercontent.com/60146935/189738169-a2236a2b-eec9-47b0-8451-f19fabc69593.gif)

<h2>How to Test</h2>

It can be tested by one or two people at once (two is preferable). THe characters are operated with WASD and ^V>< arrows. The restart is not made yet, so the only way to start game again would be to exit and enter playmode. 

Also I keep messing up left and right, so it gets confused on who won. I hope I’ll have time to fix it before class.

<h2>How to Review</h2>

What do you think about speed of fireballs?

What about overall balance?

How intuitive is the game?

What about balance? Is it too much health? Is the shield feels helpful?

Is there any advice on characters?

If anyone points any issues with interface/game/experience, I would be glad to know about them.

2022-09-19 03:14 UTC, redmoe requested changes
Great work! Appreciating the effort put in!

Change requests:
- Seeing empty folders in Assets (Ekatarina, MageGame 2). Check if there are residual .meta files for those folder in the Assets folder and delete them as well as the folders if so.
- Change namespaces to something less generic (mainproject -> Mai.mainproject)

2022-09-20 15:16 UTC, zaksaja reviewed
Looks great, I really loved the gameplay and the sprite animations! The overall feel of the game is classic arcade with a more complex and aesthetically pleasing art style.

2022-09-21 20:51 UTC, redmoe approved these changes

2022-09-21 20:53 UTC, babybabel approved these changes
so cool bestie

2022-09-21 20:53 UTC, merged