Aisha/arcade2
jli-systems-games/FA22-class-repo pull request #22
Opened 2022-09-12 21:20 UTC by gamesbyaisha

https://www.notion.so/System-Game-Project-Writing-ac3949cb2bee484386edfe545c6c06e0

<h2>Summary</h2>
 
This PR contains all the process for my arcade game called HOT RAID. The final game version should be here as well. You are a water droplet, and you need to escape the fire to not die. Be careful, its hot! Your score will output at the end.

<h2>Details</h2>

I created four scenes: start, play, win, and a game over scene. I made the game imitate a real-life arcade using the rounded rectangle at the borders, and using retro music, pixelated images, text, and plain colors. It is a very fast-paced game and I think it would be replayed a lot of times. I used screen boundaries to make sure the player does not exit the arcade game screen during play.

If I had more time to work on this, I would add more animations and VHS effects to make it look even more retro, I would use Aseprite to design the backgrounds for each scene and make it look more aesthetically pleasing. I would also add more levels and make it harder to win each time.

<h2>Visuals</h2>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/82407553/190952957-4f196f42-a815-40cd-b51e-08edff992251.gif)

<h2>How to Test</h2>

Playing it is very simple, just use the arrow controls. The instructions are on the screen, press any key to start playing. Press the space bar to restart the game after failing/winning, I made sure it was only the space bar because pressing any key right after death would restart the scene without the player even seeing the game over/win scene so fast. 

<h2>How to Review</h2>

What do you think about the visuals?
Is it clear that it is an arcade machine?
Advice on the logo? 
Is it coherent?
Is the speed fast/slow enough? Should it change?
How did the game make you feel?
Should I increase the timer amount?

2022-09-13 02:09 UTC, jasonzli requested changes
A fairly complex thing you've made here! Ambitious and exciting. Left comments for you to consider. The namespaces are necessary.

2022-09-13 02:09 UTC, jasonzli commented on Packages/packages-lock.json
> -      "version": "7.0.4",
You should not have these changes in your project, please undo the changes.

2022-09-13 02:09 UTC, jasonzli commented on ProjectSettings/EditorBuildSettings.asset
> +  - enabled: 1
This is fine to have but it will cause merge conflicts later, so you'll have to update these if someone merges before you

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/gameOverScreen.cs
> +public class gameOverScreen : MonoBehaviour
Capitalization, should be `GameOverScreen` for good practice.

Also missing namespace

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/boundary.cs
> +//public class boundary : MonoBehaviour
Empty class... delete?

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/boat.cs
> +        float rightEdge = 10f; //the right edge of the screen in world coordinates
I would move these to the top of the class declaration instead of here in the Update()

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/boat.cs
> +public class boat : MonoBehaviour
capitalization, `Boat`

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/boat.cs
> +
Missing namespace

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/boat.cs
> +    public Rigidbody2D rb;
rb can be made private since you're setting it in the `Start`

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/Timer.cs
> +
missing namespace

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/StonesSpawn.cs
> +
namespace

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/StonePic.cs
> +            SceneManager.LoadScene("GameOver");
"GameOver" is going to be a commonly used name between you and everyone. Perhaps you can rename the scene to something like `Aisha_Arcade_GameOver`

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/StonePic.cs
> +
namespace

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/Score.cs
> +
name space

2022-09-13 02:09 UTC, jasonzli commented on Assets/AishaBikebayeva/Arcade Game/Scripts/ChangeScene.cs
> +
namespace

2022-09-13 15:42 UTC, DinosaurPower commented
Hi Aisha!
I love the concept, the music and the visuals of the main page. The logo is bold and easy to memorize. Though, there are some improvements you can make to your project:
1) Namespace: you forgot adding namespace to your script, it may become a problem in future
2) Visuals: the visuals in main scene look slightly non-coherent with each other. Maybe you want some sprites that are coherent with into scene visuals (with color scheme and no line). Also, the background feels slightly bland, maybe you may want to add texture or pattern
3) speed: the pace of the game feels slightly too quick, it would be nice to slow down both character and obstacles
4) Also, it feels unintuitive how to win this game. Maybe you want to make some "Win" state.
On the other hand, I love the music and timer. The prototype is working and looks engaging, looking forward seeing the final project!! Hope the review helps!

2022-09-19 20:50 UTC, gamesbyaisha commented
> Hi Aisha! I love the concept, the music and the visuals of the main page. The logo is bold and easy to memorize. Though, there are some improvements you can make to your project:
> 
> 1. Namespace: you forgot adding namespace to your script, it may become a problem in future
> 2. Visuals: the visuals in main scene look slightly non-coherent with each other. Maybe you want some sprites that are coherent with into scene visuals (with color scheme and no line). Also, the background feels slightly bland, maybe you may want to add texture or pattern
> 3. speed: the pace of the game feels slightly too quick, it would be nice to slow down both character and obstacles
> 4. Also, it feels unintuitive how to win this game. Maybe you want to make some "Win" state.
>    On the other hand, I love the music and timer. The prototype is working and looks engaging, looking forward seeing the final project!! Hope the review helps!

Thank you, Maiia!! That was helpful, I did improve on the things you mentioned except the plain-colored backgrounds and I decided it is more exciting if the game is fast-paced, makes it less possible for the player to get bored quickly.

2022-09-21 21:22 UTC, redmoe approved these changes

2022-09-21 21:23 UTC, DinosaurPower approved these changes
🦅💨

2022-09-21 21:23 UTC, merged