Nickel/arcade2
jli-systems-games/FA22-class-repo pull request #26
Opened 2022-09-12 21:28 UTC by NickelXu0

[Link to check-in or debrief if applicable](link to google doc goes here)

<h2>Summary</h2>
 
What is in this PR? Is it the basis features? Is it nearly complete?

<h2>Details</h2>

What are the implementation details of what you've done? 
How did you go about making what you did?

<h2>Visuals</h2>

\[Animated GIFs here]

<h2>How to Test</h2>

- How do we play this?
- What known issues are there?

<h2>How to Review</h2>

- What do you want feedback on?
- Methods used?
- Textures?
- Look and feel?

2022-09-12 22:04 UTC, ekaterina392 commented
Hi Nickel,

I think you have created a nice multiplayer game! It was so funny to see that players can bump into each other, which I guess will add even more competition for filling the squares. Maybe you should add some time (additional 1 minute or so) as it seems too fast now, as well as make the play space bigger.

2022-09-13 02:21 UTC, jasonzli requested changes
Overall a good setup, but I recommend putting your scripts into a sub folder as well as your visual assets/aniamtions into another. Then name your scene something more descriptive and specific to you.

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/Player.cs
> +namespace NickelVampireSurvive
This is probably not the namespace you want 😆 `Nickel` will do just fine.

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/PrintScore.cs
> +public class PrintScore : MonoBehaviour
namespace

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/SceneLoader.cs
> +public class SceneLoader : MonoBehaviour
namespace

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/TerritoryChangeColor.cs
> +public class TerritoryChangeColor : MonoBehaviour
namespace

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/Timer.cs
> +public class Timer : MonoBehaviour
name space

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/Timer.cs
> +    void updateTimer(float currentTime)
capital u `UpdateTimer`

2022-09-13 02:21 UTC, jasonzli commented on Assets/NickelArcade/PrintScore.cs
> +        printPlayer1Score.GetComponent<TMP_Text>().text = "Red--" +TerritoryChangeColor.player1Score.ToString();
Does this really need to run every `Update`?

2022-09-13 02:21 UTC, jasonzli commented on ProjectSettings/TagManager.asset
> +  - Player2
Be cautious about the potential for conflicts here

2022-09-13 02:21 UTC, jasonzli commented on ProjectSettings/InputManager.asset
> +  - serializedVersion: 3
You will likely need to redo these after a merge conflict resolution

2022-09-13 02:21 UTC, jasonzli commented on ProjectSettings/EditorBuildSettings.asset
> +    path: Assets/NickelArcade/StartPage.unity
These will likely run into conflicts

2022-09-13 02:22 UTC, jasonzli commented
Your PR description is also needs to be completed

2022-09-21 20:19 UTC, zaksaja approved these changes

2022-09-21 23:26 UTC, merged

2022-10-11 07:17 UTC, NickelXu0 commented
Thank you for your advice! I will definitely try it!

ekaterina392 ***@***.***>于2022年9月12日 周一下午6:04写道：

> Hi Nickel,
>
> I think you have created a nice multiplayer game! It was so funny to see
> that players can bump into each other, which I guess will add even more
> competition for filling the squares. Maybe you should add some time
> (additional 1 minute or so) as it seems too fast now, as well as make the
> play space bigger.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jli-systems-games/FA22-class-repo/pull/26#issuecomment-1244570629>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNPNX3OJZDJKEJOELYIQQLV56SGTANCNFSM6AAAAAAQK3HVMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>