Regan/Project1
jli-systems-games/FA22-class-repo pull request #27
Opened 2022-09-12 21:29 UTC by ohh550

[Link to check-in or debrief if applicable](link to google doc goes here)

<h2>Summary</h2>
 
What is in this PR? Is it the basis features? Is it nearly complete?

<h2>Details</h2>

What are the implementation details of what you've done? 
How did you go about making what you did?

<h2>Visuals</h2>

\[Animated GIFs here]

<h2>How to Test</h2>

- How do we play this?
- What known issues are there?

<h2>How to Review</h2>

- What do you want feedback on?
- Methods used?
- Textures?
- Look and feel?

2022-09-12 21:38 UTC, gamesbyaisha approved these changes

2022-09-13 01:30 UTC, jasonzli commented
This pull request description is incomplete. And all the scripts are missing namespaces. Please fix

2022-09-13 01:32 UTC, jasonzli requested changes
Make sure all the scripts are put into namespaces before merging

2022-09-13 15:36 UTC, jasonzli commented on Assets/Regan/Project1/Scripts/UI/GameUI.cs
> +public class GameUI : MonoBehaviour
namespace

2022-09-21 23:24 UTC, merged