Max/Project1-CatPinball-Prototype
jli-systems-games/FA22-class-repo pull request #28
Opened 2022-09-12 21:30 UTC by pecom291

## Summary

- This is the prototype for the Arcade game for the first project of the semester which is a pinball game around cats! The current PR is about half complete, with the primary part of game play is complete as well but with a few bugs that need to be fixed. The overall concept for this was to have a pinball game where you play as a cat swatting a ball of yarn trying to collect treats. I designed it so that you have to click using your mouse the left or right side of the screen in order for the bumpers to move as I felt it added a bit to the game play and makes you feel a bit more involved.

## Details

- One of the first things I felt necessary to add was to make the paddles into cat paws. The scoreboard as well as the background will be primarily cats so the player already is in a happy space opening the game. Most of if not all of the necessary scripting is done but not currently being used, the goal was to roughly outline the game with placeholders and such while doing the coding and other aspects then to fix the backgrounds and everything else. I started making this from actually looking at an old project that I had that was also a 2D game. This helped me a lot in scripting and from there I proceeded to start fixing the bumpers and setting up the rest of the game just in a rough layout. After this I went ahead and threw a bunch of scripts together to try my best to get these pieces to collide and interact with one another which there are a lot of bugs but completely manageable.

## Visuals

- I actually need to ask for help on how to make a gif of it….

## How to Test

- To play this game is extremely straightforward. Your left click begins the game, and clicking on the left or right side of the screen with the left mouse button with make the paddle/bumper on that side move. The goal is to hit the ball and to collect the treats above.

- There are quite a few issues at the moment. The primary one being that the “diamonds” which are actually treats that are a current placeholders. The sound manager and bumpers were also added into the game and optimized to some random sounds that I found but I will be changing almost all of the visuals. The diamonds at the moment are supposed to break apart when they are touched but that doesn’t happen when you do.

## How to Review

- I would like feedback on how the game plays feels and how the content feels as a whole. What do you think needs improvement? Is the concept good? Are there any little things for me to add that you feel could improve it overall?
- I also want to know if you think there are any betters ways for to have done anything, do you think the ball should be bigger, the spawn points in different places?

2022-09-13 02:35 UTC, jasonzli requested changes
Looks interesting and certainly engineered. I'd like to know where the old project came from. Is it entirely your work? Did you learn this from another source?

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/Ball.cs
> +public class Ball : MonoBehaviour
Namespace

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/Bouncer.cs
> +public class Bouncer : MonoBehaviour
namespace

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/Diamond.cs
> +public class Diamond : MonoBehaviour
namespace

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/Diamond.cs
> +            Loader.fillAmount = 1 - timeToEnd / 10.0f;
a classic creative coding pattern 👍

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/FlippersBehaviour.cs
> +public class FlippersBehaviour : MonoBehaviour
namespace

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/FlippersBehaviour.cs
> +    private float tourque;
`torque` spelling

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/FlippersBehaviour.cs
> +#if UNITY_EDITOR
Where did you learn this?

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/SoundManager.cs
> +public class SoundManager : MonoBehaviour
Namespace

2022-09-13 02:35 UTC, jasonzli commented on Assets/MaxPecora/Assets/Pinball Asset/Scripts/UIManager.cs
> +public class UIManager : MonoBehaviour
namespace

2022-09-13 20:16 UTC, MarioBrnjac approved these changes
The way the ball reacts to getting hit is very smooth. I think that right now, it can sometimes move too fast after getting hit and giving it some drag so that it can slow down a bit after getting hit can make it more controllable.

2022-09-16 04:18 UTC, DinosaurPower commented
Hi Max! Sorry for late feedback!
First of all, I totally love the theme combination and the physics of the ball. They have this _feel_ that make game dynamic but also realistic in their response.
On the other hand, I've noticed few issues.
First of all, I would add keyboard controls so that it would be accessible both from mobile device and compewter just for easier playtesting. 
ANother thing I would add is background for menu as the dark text is hard to read on dark background.
Additionally, I wanted to notice your work on the different calculations (as like score and amount of games played), it gives game some extra feedback towards player, what adds this extra serotonin to the overall experience. 
Good job!!! Looking forward the final version!!

2022-09-18 15:19 UTC, redmoe commented
To create a gif, use a screen recorder such as [LICEcap](https://www.cockos.com/licecap/). Set the window size to be around Unity game view and then hit record. There should be an option to "Automatically Stop After" X number of seconds, consider setting it to about 5.

You can then switch to Unity and play the game while recording.

2022-09-18 22:53 UTC, pecom291 reviewed
I actually used a combination of knowledge from a friend in terms of coding to help put this part together, he also helped greatly in helping organize the code. I did however primarily reference some code from previous 2D games I've made from last year and semester!

2022-09-21 21:00 UTC, redmoe approved these changes

2022-09-21 21:00 UTC, merged