Samantha/maze2
jli-systems-games/FA22-class-repo pull request #31
Opened 2022-09-12 21:49 UTC by zaksaja

[Link to check-in or debrief if applicable](link to google doc goes here)

<h2>Summary</h2>
 
What is in this PR? Is it the basis features? Is it nearly complete?

<h2>Details</h2>

What are the implementation details of what you've done? 
How did you go about making what you did?

<h2>Visuals</h2>

\[Animated GIFs here]

<h2>How to Test</h2>

- How do we play this?
- What known issues are there?

<h2>How to Review</h2>

- What do you want feedback on?
- Methods used?
- Textures?
- Look and feel?

2022-09-13 02:42 UTC, jasonzli requested changes
Looks like we're in the beginning stages of this project.

Namespaces are missing, but the big thing that is problematic is all the URP, project changes and miscellaneous .meta files that shouldn't be in here.

Reorganize your project and also delete the extra files that you don't need.

Need to fill out the PR description!

2022-09-13 02:42 UTC, jasonzli commented on Assets/samantha zak/Scripts/PlayerControl1.cs
> +public class PlayerControl : MonoBehaviour
namespace, but this class is empty? Placeholder?

2022-09-13 02:42 UTC, jasonzli commented on Assets/samantha zak/Scripts/PlayerMove.cs
> +public class PlayerMove : MonoBehaviour
Also an empty class? Is this a placeholder?

2022-09-13 02:42 UTC, jasonzli commented on Assets/samantha zak/Scripts/PlayerMovement.cs
> +public class PlayerMovement : MonoBehaviour
Namespace

2022-09-15 20:39 UTC, pecom291 approved these changes
This is actually really cool though I will admit I could not find the exit ):. I think the game play is great and the idea to make the spinning objects have collision and move with you is a really cool game aspect. Adding more walls and obstacles to it will definitely help as the obstacles kind of give an idea of where players can go (or fool them). Overall I think it's coming along great and I'd happily play it when its updated again!

2022-09-19 02:22 UTC, redmoe requested changes
Game is looking good!
- [x] Move assets into a folder into a separate game folder inside of your named folder ( Assets/samantha zak -> Assets/samantha zak/Arcade)
- [ ] Add namespaces to scripts (see Jason's comments)
- [ ] Move assets outside of your game's folder into your game's folder (ObstacleAssetStars, Bouncy, hinge1)

2022-09-21 23:22 UTC, merged