Wei Arcade Game
jli-systems-games/FA22-class-repo pull request #34
Opened 2022-09-12 22:15 UTC by Weeeeeeeeei

<h2>Summary</h2>
 
A Snake & Bullet Game

<h2>Details</h2>

The player controls the snake to eat the barrage, and each barrage eaten can increase the size and speed, but the barrage hits the body will reduce the size.

<h2>Visuals</h2>

![download](https://user-images.githubusercontent.com/89833739/189740466-b649602b-c464-407d-baca-d376582bc9d5.gif)

<h2>How to Test</h2>

- How do we play this?
WASD
- What known issues are there?
player can't eat the bullet yet, and the wall couldn't stop the snake

<h2>How to Review</h2>

- What do you want feedback on?
how to do trigger

2022-09-12 22:27 UTC, ekaterina392 commented
Hi Wei,

I figured out only how to control the snake but I did not get any collision with the white circles. Maybe you are planning to make them as obstacles in the future?
I think you should change a little the movements of the snake, probably make them smoother and faster, because it is not obvious that the snake can move at the first glance.

2022-09-13 02:48 UTC, jasonzli requested changes
Exciting start! Needs namespaces but you've organized things well. Consider a more specific scene name.

2022-09-13 02:48 UTC, jasonzli commented on Assets/Wei Wu/scripts/AppleController.cs
> +public class AppleController : MonoBehaviour
namespace

2022-09-13 02:48 UTC, jasonzli commented on Assets/Wei Wu/scripts/CameraFollow.cs
> +public class CameraFollow : MonoBehaviour
namespaces

2022-09-13 02:48 UTC, jasonzli commented on Assets/Wei Wu/scripts/FirePoint.cs
> +public class FirePoint : MonoBehaviour
namespace

2022-09-13 02:48 UTC, jasonzli commented on Assets/Wei Wu/scripts/SnakeController.cs
> +public class SnakeController : MonoBehaviour
namespace

2022-09-19 20:37 UTC, Hectorgamecreator commented
The game art is amazing; I loved the story plot behind the snake game. I would like to see if you have a game title for your loading screen. Overall, I had a fun time trying to collect as many eggs as I could.  Also, what is your game's screen size for the game?

2022-09-21 23:26 UTC, closed without merging