Mariana/arcade game
jli-systems-games/FA22-class-repo pull request #35
Opened 2022-09-12 22:21 UTC by m-holtz

<h2>Summary</h2>
 
This is an early prototype of my arcade game. In this version, I focused on adding the basic mechanics that the game would need to run, with no final art yet. As of right now, the player is able to interact with a "START" screen, move the players with arrow keys to run away from the enemies, and lose if they collapse with an enemy or if the timer runs out. There is no way to win this game yet.

<h2>Details</h2>

Player:
 - The player moves around with arrow keys.
Enemies: 
 - Enemies follow the player.
 - If enemies collides with player, it loads the "game over" scene (EndBad)
 - There are multiple enemies, but they are turned off (I am changing to spawn randomly)
TImer:
 - 60 seconds timer.
 - When your run out of time, the "game over" screen loads.

<h2>Visuals</h2>

![Arcade-1](https://user-images.githubusercontent.com/74580132/189768477-34c1277d-71cd-4ba1-a0ba-4fb405da08af.gif)

<h2>How to Test</h2>

- How do we play this?   
      -Use arrow keys to run away from enemies
- What known issues are there?
      -  You can’t kill enemies, so you can never win
    

<h2>How to Review</h2>

How is the speed of the player/enemy? Should one of them be slower or faster?
Is 60 seconds too long?

2022-09-13 03:36 UTC, jasonzli requested changes
I like where this is headed! Namespace and scene loading considerations suggested for you.

2022-09-13 03:36 UTC, jasonzli commented on Assets/Mariana /Script/PlayerCollisionWEnemy.cs
> +            SceneManager.LoadScene(2);
This seems like a very specific thing to have it do.

Scene "2" might also change as this project develops, which might cause a conflict with other projects.

2022-09-13 03:36 UTC, jasonzli commented on ProjectSettings/EditorBuildSettings.asset
> +    path: Assets/Mariana /Scenes/EndBad.unity
Scene changes are fine! You had to update build settinsg to get this to work but it will have an issue with people down the road.

2022-09-13 03:36 UTC, jasonzli commented on Assets/Mariana /Script/SceneLoadManager.cs
> +        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);
Unfortunately, this is going to be unreliable long term since the scene index will change over the life of the project.

2022-09-13 03:36 UTC, jasonzli commented on Assets/Mariana /Script/Timerend.cs
> +                SceneManager.LoadScene(2);
Same as those other comments regarding scene reliability. Scene name will be better

2022-09-21 21:44 UTC, redmoe approved these changes

2022-09-21 21:45 UTC, babybabel approved these changes

2022-09-21 21:48 UTC, merged