Hector/pacman3
jli-systems-games/FA22-class-repo pull request #37
Opened 2022-09-15 03:46 UTC by Hectorgamecreator

[Link to check-in or debrief if applicable](link to google doc goes here)

<h2>Summary</h2>
 
What is in this PR? Is it the basic features? Is it nearly complete?
This is a prototype of a Pacman game.  I am changing Pacman to a cactus and ghost to fireballs. The basic controls I have right now are animating the Pacman and moving the player around the maze.  The final version should have the cactus player collecting as many water pellets before getting eliminated by the fireballs.

<h2>Details</h2>

What are the implementation details of what you've done? 
-cactus are animated.
-fireballs are animated.
-The cactus has to collect all the water pellets to win the game. 
-Fireballs are ai enemies chasing the cactus.

How did you go about making what you did?
During this game set up, I understood the mechanics behind Pacman and used it for my cactus game. I think the design for the ai fireballs was interesting as their movement gets affected by node checkpoints.

<h2>Visuals</h2>

https://user-images.githubusercontent.com/89846649/190308697-7fb2f9e0-c3c5-4d34-930e-94a27696e1b0.mov

https://user-images.githubusercontent.com/89846649/190308443-ac28beba-70a1-49d6-93e8-78f72a4713d2.mov

<h2>How to Test</h2>

- How do we play this?
-  up, down, left, and right arrows will be your controls for your player.
-Collect all the water pellets before getting eliminated by the fireballs. 

- What known issues are there?
- The fireballs get attached to the nearest walls once they leave their home checkpoint. 

<h2>How to Review</h2>

- What do you want feedback on?
- How could I try to fix my fireballs getting stuck to my walls? 

- Methods used?
- I used procreate to create my sprites.
-I am using sprites and scripts Zigurous on Youtube. 

- Textures?
- Look and feel?
- I am going for a desert theme that involves a cactus collecting water before the fireballs chase him.

2022-09-16 03:56 UTC, DinosaurPower commented
Hello hello! Time for revision!!
Some issues I've met for now:
•You forgot namespace in your code, that will become a problem when we will be merging projects
•My Unity complained that prefabs for ghosts went missing. Does it have to be this way?
•I couldn't make pacman move in the scene more than for few milimeters and enemies were missing. Is it supposed to be that way?
On the other hand, I love detalisation and animations, as well as I appreciate amount of code and its quality. Good job with that!! And I love the creative approach towards modification of classical arcade! Also really looking forward seeing cactus sprite in the project!! Maybe you can build up on cactus idea and make background more desert-themed.
On regards of your question, I couldn't check the exact issue on fireballs getting stuck as there was no depiction of them in action and nodes are not my strongest specialisation, but  there are few things you may try to fix this:
1) Fix the missing prefab glitch: errors often make Unity work weird
2) Try switching walls state to static from dynamic, it helps sometimes
3) try making some code that will help fireballs avoid walls/change direction on interacting with them
Overall, I love the whole initiative, but there are few major glitches that don't allow me to appreciate all the tremendous work you did with coding! Good luck with your game! Looking forward seeing it on presentation!!

2022-09-18 22:06 UTC, MarioBrnjac reviewed
The overall gameplay is very fun and works well. When I load up the "Pacman" scene in unity it says that there are errors and prefabs missing, however I didn't have any issues when I played the game by starting it through the title screen. The logo on the title screen is kinda small and not centered and the "click to play" button is halfway off the screen. At some times the character wouldn't want to turn left and right to make turns or I would have had to spam it to get them to turn, but it wasn't very common to happen.

2022-09-19 02:53 UTC, redmoe requested changes
- [ ] Add namespace to all scripts, example:
```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Hector {
[RequireComponent(typeof(SpriteRenderer))]
public class AnimatedSprite : MonoBehaviour
  {
  //code
  }
}
```

2022-09-21 22:53 UTC, jasonzli approved these changes

2022-09-21 22:54 UTC, merged